### ISSUE TITLE
建议延长下token的有效期，客户端经常要输入密码登录影响体验

### ISSUE THREAD

**Issue by chenhengjie123** [testerhome/ruby-china-ios#7]
建议延长下token的有效期，客户端经常要输入密码登录影响体验

来自 https://testerhome.com/topics/6604#reply53

**Comment by huacnlee** [comment]
后台“/admin/applications”可以设置 level 

level:

| level | 有效期 |
|------|-------|
| 0 | 默认 1.days |
| 1 | 7.days |
| 2 | 14.days |
| 3 | 30.days |

**Comment by chenhengjie123** [comment]
谢谢华顺，已把 iOS 客户端后台配置改为了 3 ，即有效期30天。
